# Generated by Django 5.0.3 on 2024-03-08 09:42

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('post_name', models.CharField(max_length=1000)),
                ('post_image', models.FileField(upload_to='post_images')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('no_of_likes', models.IntegerField()),
            ],
        ),
    ]
