# Generated by Django 5.0.3 on 2024-03-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
